import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase";

/**
 * GET /api/litt/artifacts
 *
 * Returns artifacts generated by LiTT runs. Supports filtering by
 * run, project, and type. Artifacts include generated files, images,
 * videos, audio, and other outputs.
 *
 * Query params:
 *   runId    — filter by run
 *   projectId — filter by project
 *   type     — filter by artifact type (file, image, video, audio, music)
 */
export async function GET(request: NextRequest) {
  const { userId } = await auth(request);
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!supabaseAdmin) {
    return NextResponse.json({ error: "Database unavailable" }, { status: 503 });
  }

  // Resolve internal user ID
  const { data: user } = await supabaseAdmin
    .from("users")
    .select("id")
    .eq("clerk_id", userId)
    .maybeSingle();

  if (!user) {
    return NextResponse.json({ error: "User not found" }, { status: 404 });
  }

  const runId = request.nextUrl.searchParams.get("runId");
  const projectId = request.nextUrl.searchParams.get("projectId");

  // Query mission_artifacts (the existing artifacts table)
  let query = supabaseAdmin
    .from("mission_artifacts")
    .select("*")
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .limit(50);

  if (runId) {
    query = query.eq("mission_run_id", runId);
  }
  if (projectId) {
    query = query.eq("project_id", projectId);
  }

  const { data: artifacts, error } = await query;

  if (error) {
    return NextResponse.json({ error: "Failed to fetch artifacts" }, { status: 500 });
  }

  return NextResponse.json({
    artifacts: (artifacts ?? []).map((a) => ({
      id: a.id,
      type: a.artifact_type,
      name: a.name,
      url: a.url,
      metadata: a.metadata,
      runId: a.mission_run_id,
      projectId: a.project_id,
      createdAt: a.created_at,
    })),
  });
}
