-- ============================================
-- Studio Projects (GitHub-backed)
-- This is the canonical schema; the migration in
-- supabase/migrations/20260720000000_studio_projects_github.sql
-- is the source of truth. This file is kept for reference.
-- ============================================
-- See migration file for full DDL + RLS.
-- Run the migration via Supabase SQL Editor or:
--   supabase db push
-- ============================================
