/**
 * Cross-user isolation tests — P0-6
 *
 * Verifies that User B cannot read, write, delete, or enumerate resources
 * owned by User A, across every user-scoped API surface.
 *
 * Requirements
 * ─────────────
 * • PLAYWRIGHT_INTEGRATION=true (activates self-contained-auth project)
 * • Auth files in tests/playwright/.clerk/ (generated by auth-setup project)
 *   — user-a.json  (storage state for CLERK_TEST_USER_A_EMAIL)
 *   — user-b.json  (storage state for CLERK_TEST_USER_B_EMAIL)
 * • A running Next.js server (pnpm start / pnpm dev)
 *
 * Run locally:
 *   PLAYWRIGHT_INTEGRATION=true pnpm exec playwright test isolation --project=self-contained-auth
 *
 * These tests are deliberately EXCLUDED from the blocking CI Playwright step
 * (public-chromium/firefox/webkit) so that CI never fails solely because test
 * auth files are absent. They run as non-blocking in CI via the
 * self-contained-auth project when PLAYWRIGHT_INTEGRATION=true is set.
 *
 * Design principles
 * ─────────────────
 * • Tests are serial: each test depends on state from the previous one.
 * • Cleanup always runs (afterAll), even if setup or assertion tests fail.
 * • All assertions use 404 (not 403) for cross-user access — routes return a
 *   generic "not found" for both "resource missing" and "not your resource" to
 *   avoid leaking resource existence to a foreign user.
 * • API-only tests (no browser navigation) — faster and more reliable.
 */

import { test, expect } from "@playwright/test";
import path from "path";
import { existsSync } from "fs";

// ── Auth file paths ──────────────────────────────────────────────────────────
const authDir = path.join(__dirname, ".clerk");
const userAFile = path.join(authDir, "user-a.json");
const userBFile = path.join(authDir, "user-b.json");

const authFilesExist = existsSync(userAFile) && existsSync(userBFile);

// ── Shared state set up by the first describe block ──────────────────────────
// These are set during "setup" and read during "isolation checks".
const state: {
  projectId: string | null;
  conversationId: string | null;
  approvalId: string | null;
} = {
  projectId: null,
  conversationId: null,
  approvalId: null,
};

// ── Skip guard ────────────────────────────────────────────────────────────────
// When auth files don't exist (fresh checkout, no auth-setup run yet) skip
// gracefully rather than failing with an opaque "storage state not found" error.
function requireAuthFiles() {
  if (!authFilesExist) {
    test.skip(
      !authFilesExist,
      "Auth files missing — run `pnpm exec playwright test --project=auth-setup` first",
    );
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// PART 1 — Authentication gate (no auth required)
// These run even without auth files and verify that every user-scoped route
// returns 401 for anonymous requests, not 200 or a data leak.
// ═══════════════════════════════════════════════════════════════════════════════

test.describe("Auth gates — anonymous requests must be 401", () => {
  const syntheticId = "00000000-0000-0000-0000-000000000001";

  test("GET /api/studio-projects returns 401 for anon", async ({ request }) => {
    const res = await request.get("/api/studio-projects");
    expect(res.status()).toBe(401);
  });

  test("GET /api/studio-projects/:id returns 401 for anon", async ({ request }) => {
    const res = await request.get(`/api/studio-projects/${syntheticId}`);
    expect(res.status()).toBe(401);
  });

  test("DELETE /api/studio-projects/:id returns 401 for anon", async ({ request }) => {
    const res = await request.delete(`/api/studio-projects/${syntheticId}`);
    expect(res.status()).toBe(401);
  });

  test("PATCH /api/studio-projects/:id returns 401 for anon", async ({ request }) => {
    const res = await request.patch(`/api/studio-projects/${syntheticId}`, {
      data: { name: "injected-name" },
    });
    expect(res.status()).toBe(401);
  });

  test("GET /api/conversations returns 401 for anon", async ({ request }) => {
    const res = await request.get("/api/conversations");
    expect(res.status()).toBe(401);
  });

  test("GET /api/approvals/:id returns 401 for anon", async ({ request }) => {
    const res = await request.get(`/api/approvals/${syntheticId}`);
    expect(res.status()).toBe(401);
  });

  test("GET /api/studio-projects/:id/files returns 401 for anon", async ({ request }) => {
    const res = await request.get(`/api/studio-projects/${syntheticId}/files`);
    expect(res.status()).toBe(401);
  });

  test("POST /api/studio-projects/:id/files (write) returns 401 for anon", async ({ request }) => {
    const res = await request.post(`/api/studio-projects/${syntheticId}/files`, {
      data: { action: "write", path: "test.txt", content: "x" },
    });
    expect(res.status()).toBe(401);
  });

  test("POST /api/studio-projects/:id/files (delete) returns 401 for anon", async ({ request }) => {
    const res = await request.post(`/api/studio-projects/${syntheticId}/files`, {
      data: { action: "delete", path: "test.txt" },
    });
    expect(res.status()).toBe(401);
  });

  test("POST /api/ai-chat returns 401 for anon", async ({ request }) => {
    const res = await request.post("/api/ai-chat", {
      data: { messages: [{ role: "user", content: "hello" }] },
    });
    expect(res.status()).toBe(401);
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
// PART 2 — Cross-user isolation (requires auth files)
// ═══════════════════════════════════════════════════════════════════════════════

// ── SETUP: User A creates resources ─────────────────────────────────────────

test.describe.serial("Setup: User A creates test resources", () => {
  test.use({ storageState: userAFile });
  test.beforeAll(requireAuthFiles);

  test("User A can create a project", async ({ request }) => {
    const res = await request.post("/api/studio-projects", {
      data: { name: `isolation-test-${Date.now()}` },
    });
    // Accept 200 or 201
    expect([200, 201]).toContain(res.status());
    const body = await res.json();
    state.projectId = body?.project?.id ?? null;
    expect(state.projectId).toBeTruthy();
  });

  test("User A can fetch their own project", async ({ request }) => {
    if (!state.projectId) test.skip(true, "Project not created in setup");
    const res = await request.get(`/api/studio-projects/${state.projectId}`);
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.project.id).toBe(state.projectId);
  });

  test("User A can list their conversations", async ({ request }) => {
    const res = await request.get("/api/conversations");
    expect(res.status()).toBe(200);
    // Just verifying the endpoint works; conversation creation needs an agent
    const body = await res.json();
    expect(body).toHaveProperty("conversations");
    expect(Array.isArray(body.conversations)).toBe(true);
    // Store first conversation ID if available
    if (body.conversations.length > 0) {
      state.conversationId = body.conversations[0].id;
    }
  });
});

// ── ISOLATION: User B cannot access User A's resources ──────────────────────

test.describe.serial("Isolation: User B cannot access User A resources", () => {
  test.use({ storageState: userBFile });
  test.beforeAll(requireAuthFiles);

  // ── Projects ────────────────────────────────────────────────────────────────

  test("User B gets 404 reading User A project", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.get(`/api/studio-projects/${state.projectId}`);
    // Must be 404, not 200 (data leak) or 403 (existence leak)
    expect(res.status()).toBe(404);
  });

  test("User B gets 404 deleting User A project", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.delete(`/api/studio-projects/${state.projectId}`);
    expect(res.status()).toBe(404);
    // Verify the project still exists (User A can still fetch it)
  });

  test("User B gets 404 renaming User A project", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.patch(`/api/studio-projects/${state.projectId}`, {
      data: { name: "user-b-renamed" },
    });
    expect(res.status()).toBe(404);
  });

  test("User B gets 404 reading User A project files", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.get(`/api/studio-projects/${state.projectId}/files`);
    expect(res.status()).toBe(404);
  });

  test("User B gets 404 writing to User A project files", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.post(`/api/studio-projects/${state.projectId}/files`, {
      data: { action: "write", path: "injected.txt", content: "pwned" },
    });
    expect(res.status()).toBe(404);
  });

  test("User B gets 404 deleting from User A project files", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.post(`/api/studio-projects/${state.projectId}/files`, {
      data: { action: "delete", path: "README.md" },
    });
    expect(res.status()).toBe(404);
  });

  test("User B GET /api/studio-projects does NOT include User A projects", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.get("/api/studio-projects");
    expect(res.status()).toBe(200);
    const body = await res.json();
    const projects: Array<{ id: string }> = body?.projects ?? body?.data ?? [];
    const leaked = projects.find((p) => p.id === state.projectId);
    expect(leaked).toBeUndefined();
  });

  // ── Conversations ────────────────────────────────────────────────────────────

  test("User B GET /api/conversations does NOT include User A conversations", async ({ request }) => {
    if (!state.conversationId) test.skip(true, "No conversation to test against");
    const res = await request.get("/api/conversations");
    expect(res.status()).toBe(200);
    const body = await res.json();
    const convs: Array<{ id: string }> = body?.conversations ?? [];
    const leaked = convs.find((c) => c.id === state.conversationId);
    expect(leaked).toBeUndefined();
  });

  // ── Checkpoints ─────────────────────────────────────────────────────────────

  test("User B gets 404 listing User A project checkpoints", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.get(
      `/api/studio-projects/${state.projectId}/checkpoints`,
    );
    expect(res.status()).toBe(404);
  });

  test("User B gets 404 creating checkpoint on User A project", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to test against");
    const res = await request.post(
      `/api/studio-projects/${state.projectId}/checkpoints`,
      { data: { label: "user-b-injected-checkpoint" } },
    );
    expect(res.status()).toBe(404);
  });
});

// ── VERIFICATION: User A's resource was NOT mutated by User B's attempts ────

test.describe.serial("Verification: User A resources intact after User B attempts", () => {
  test.use({ storageState: userAFile });
  test.beforeAll(requireAuthFiles);

  test("User A project still exists and name is unchanged", async ({ request }) => {
    if (!state.projectId) test.skip(true, "No project to verify");
    const res = await request.get(`/api/studio-projects/${state.projectId}`);
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.project.id).toBe(state.projectId);
    // Name must NOT have been changed by User B's PATCH attempt
    expect(body.project.name).not.toBe("user-b-renamed");
  });
});

// ── TEARDOWN: User A deletes test resources ───────────────────────────────────

test.describe.serial("Teardown: User A cleans up test resources", () => {
  test.use({ storageState: userAFile });
  test.beforeAll(requireAuthFiles);

  test("User A deletes isolation test project", async ({ request }) => {
    if (!state.projectId) return; // nothing to clean up
    const res = await request.delete(`/api/studio-projects/${state.projectId}`);
    // 200 or 404 both acceptable (idempotent teardown)
    expect([200, 404]).toContain(res.status());
    state.projectId = null;
  });
});
