/**
 * LiTT Model Catalog — V1 full lineup
 *
 * This is the canonical catalog. Both the web runtime and the CLI import from
 * here — there is ONE model catalog, not two.
 *
 * Verification policy:
 *   Every entry starts with verified:false, source:"unverified". A model is
 *   only marked verified:true when the exact providerModelId / openRouterModelId
 *   has been confirmed against a live provider or OpenRouter catalog during a
 *   real check. Never fabricate verification.
 *
 *   Dynamic provider /models discovery remains runtime truth and can override
 *   static availability. The registry's mergeDiscovered() picks up new models
 *   without a catalog rewrite.
 *
 * Catalog identity vs routing preference:
 *   This catalog describes actual models that exist. It does NOT remove a
 *   model just because another model fills the same routing role. The router
 *   (router.ts) decides which model is preferred for a given task — that is
 *   routing logic, not catalog logic.
 */

import type { ModelDefinition } from "./types";

// ─── Helper shorthand for common capability sets ───────────────────
const FULL_CHAT = {
  chat: true,
  reasoning: true,
  coding: true,
  vision: true,
  tools: true,
  audio: false,
  imageGeneration: false,
  videoGeneration: false,
  longContext: false,
  structuredOutput: true,
};
const TEXT_CHAT = {
  chat: true,
  reasoning: true,
  coding: true,
  vision: false,
  tools: true,
  audio: false,
  imageGeneration: false,
  videoGeneration: false,
  longContext: false,
  structuredOutput: true,
};

// ─── OpenAI — GPT-5.6 family (Luna / Terra / Sol) ──────────────────
const OPENAI_MODELS: ModelDefinition[] = [
  {
    canonicalId: "gpt-5.6-luna",
    displayName: "GPT-5.6 Luna",
    provider: "openai",
    providerModelId: "gpt-5.6-luna",
    openRouterModelId: "openai/gpt-5.6-luna",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 1_050_000,
    pricing: { inputPer1M: 0.2, outputPer1M: 1.2, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Cost-sensitive, high-volume. Default fast chat + quick agent loops.",
    recommendedFor: ["fast", "chat", "coding-fast", "agent"],
    littRecommended: true,
    littTier: "fast",
    domain: "text",
    maxOutputTokens: 128_000,
    reasoningEfforts: ["xhigh", "high", "medium", "low", "none"],
  },
  {
    canonicalId: "gpt-5.6-terra",
    displayName: "GPT-5.6 Terra",
    provider: "openai",
    providerModelId: "gpt-5.6-terra",
    openRouterModelId: "openai/gpt-5.6-terra",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "balanced",
    contextWindow: 1_050_000,
    pricing: { inputPer1M: 2, outputPer1M: 12, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Intelligence/cost balance. Everyday coding + stronger reasoning.",
    recommendedFor: ["balanced", "coding", "reasoning", "agent"],
    littRecommended: true,
    littTier: "balanced",
    domain: "text",
    maxOutputTokens: 128_000,
    reasoningEfforts: ["xhigh", "high", "medium", "low", "none"],
  },
  {
    canonicalId: "gpt-5.6-sol",
    displayName: "GPT-5.6 Sol",
    provider: "openai",
    providerModelId: "gpt-5.6-sol",
    openRouterModelId: "openai/gpt-5.6-sol",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 1_050_000,
    pricing: { inputPer1M: 5, outputPer1M: 30, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Frontier model for complex professional work, planning, hard reasoning.",
    recommendedFor: ["max", "reasoning", "coding", "architecture", "agent"],
    littRecommended: true,
    littTier: "max",
    domain: "text",
    maxOutputTokens: 128_000,
    reasoningEfforts: ["max", "xhigh", "high", "medium", "low", "none"],
  },
];

// ─── Anthropic — Claude 5 family ───────────────────────────────────
const ANTHROPIC_MODELS: ModelDefinition[] = [
  {
    canonicalId: "claude-haiku-4-5",
    displayName: "Claude Haiku 4.5",
    provider: "anthropic",
    providerModelId: "claude-haiku-4-5",
    openRouterModelId: "anthropic/claude-haiku-4-5",
    capabilities: { ...FULL_CHAT, longContext: false },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 200_000,
    pricing: { inputPer1M: 1, outputPer1M: 5, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Fastest Claude with near-frontier intelligence.",
    recommendedFor: ["fast", "chat"],
    domain: "text",
    maxOutputTokens: 64_000,
  },
  {
    canonicalId: "claude-sonnet-5",
    displayName: "Claude Sonnet 5",
    provider: "anthropic",
    providerModelId: "claude-sonnet-5",
    openRouterModelId: "anthropic/claude-sonnet-5",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 1_000_000,
    pricing: { inputPer1M: 2, outputPer1M: 10, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Best speed/intelligence balance. Strong general + coding.",
    recommendedFor: ["alternative", "coding", "reasoning", "balanced"],
    littRecommended: true,
    littTier: "alternative",
    domain: "text",
    maxOutputTokens: 128_000,
  },
  {
    canonicalId: "claude-opus-5",
    displayName: "Claude Opus 5",
    provider: "anthropic",
    providerModelId: "claude-opus-5",
    openRouterModelId: "anthropic/claude-opus-5",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 1_000_000,
    pricing: { inputPer1M: 5, outputPer1M: 25, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Complex agentic coding and enterprise work.",
    recommendedFor: ["deep", "coding", "reasoning", "architecture"],
    littRecommended: true,
    littTier: "deep",
    domain: "text",
    maxOutputTokens: 128_000,
  },
  {
    canonicalId: "claude-fable-5",
    displayName: "Claude Fable 5",
    provider: "anthropic",
    providerModelId: "claude-fable-5",
    openRouterModelId: "anthropic/claude-fable-5",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "slow",
    intelligence: "frontier",
    contextWindow: 1_000_000,
    pricing: { inputPer1M: 10, outputPer1M: 50, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Most capable widely released Claude. Long-running agents, hardest work.",
    recommendedFor: ["max", "deep", "reasoning", "long-running"],
    littRecommended: true,
    littTier: "deep",
    domain: "text",
    maxOutputTokens: 128_000,
  },
];

// ─── Google — Gemini 3.x Flash family ──────────────────────────────
const GOOGLE_MODELS: ModelDefinition[] = [
  {
    canonicalId: "gemini-3.7-flash",
    displayName: "Gemini 3.7 Flash",
    provider: "google",
    providerModelId: "gemini-3.7-flash",
    openRouterModelId: "google/gemini-3.7-flash",
    capabilities: { ...FULL_CHAT, audio: true, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 1_048_576,
    pricing: { inputPer1M: 0.375, outputPer1M: 1.875, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Latest Flash. Fast multimodal/agent workflows, complex multi-step reasoning.",
    recommendedFor: ["gemini", "fast", "vision", "multimodal", "agent"],
    littRecommended: true,
    littTier: "gemini",
    domain: "text",
    maxOutputTokens: 65_536,
    reasoningEfforts: ["high", "medium", "low"],
  },
  {
    canonicalId: "gemini-3.6-flash",
    displayName: "Gemini 3.6 Flash",
    provider: "google",
    providerModelId: "gemini-3.6-flash",
    openRouterModelId: "google/gemini-3.6-flash",
    capabilities: { ...FULL_CHAT, audio: true, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 1_048_576,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Previous-gen Flash. Speed + multimodal across general agentic tasks.",
    recommendedFor: ["gemini", "fast", "vision"],
    domain: "text",
    maxOutputTokens: 65_536,
  },
  {
    canonicalId: "gemini-3.5-flash",
    displayName: "Gemini 3.5 Flash",
    provider: "google",
    providerModelId: "gemini-3.5-flash",
    openRouterModelId: "google/gemini-3.5-flash",
    capabilities: { ...FULL_CHAT, audio: true, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 1_048_576,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Legacy Flash. Baseline speed for routine high-throughput workloads.",
    recommendedFor: ["gemini", "balanced", "vision"],
    domain: "text",
    maxOutputTokens: 65_536,
  },
  {
    canonicalId: "gemini-3.5-flash-lite",
    displayName: "Gemini 3.5 Flash-Lite",
    provider: "google",
    providerModelId: "gemini-3.5-flash-lite",
    openRouterModelId: "google/gemini-3.5-flash-lite",
    capabilities: { ...FULL_CHAT, audio: true, longContext: true },
    speed: "ultra",
    intelligence: "light",
    contextWindow: 1_048_576,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Fastest, most cost-effective 3.5 model for high-throughput execution.",
    recommendedFor: ["gemini", "fast", "cheap"],
    domain: "text",
    maxOutputTokens: 65_536,
  },
  {
    canonicalId: "gemini-3.1-pro",
    displayName: "Gemini 3.1 Pro",
    provider: "google",
    providerModelId: "gemini-3.1-pro-preview",
    openRouterModelId: "google/gemini-3.1-pro-preview",
    capabilities: { ...FULL_CHAT, audio: true, longContext: true },
    speed: "slow",
    intelligence: "frontier",
    contextWindow: 1_048_576,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Advanced reasoning, agentic + vibe coding. Preview endpoint.",
    recommendedFor: ["gemini", "deep", "reasoning", "coding"],
    domain: "text",
    notes: "Preview endpoint — use gemini-3.1-pro-preview as the direct API id.",
  },
];

// ─── xAI — Grok ────────────────────────────────────────────────────
const XAI_MODELS: ModelDefinition[] = [
  {
    canonicalId: "grok-4.6",
    displayName: "Grok 4.6",
    provider: "xai",
    providerModelId: "grok-4.6",
    openRouterModelId: "x-ai/grok-4.6",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 500_000,
    pricing: { inputPer1M: 2, outputPer1M: 6, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "xAI's smartest model. Frontier coding, knowledge work, STEM.",
    recommendedFor: ["alternative", "coding", "reasoning", "agent"],
    domain: "text",
    reasoningEfforts: ["xhigh", "high", "medium", "low"],
  },
  {
    canonicalId: "grok-4.5",
    displayName: "Grok 4.5",
    provider: "xai",
    providerModelId: "grok-4.5",
    openRouterModelId: "x-ai/grok-4.5",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 500_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Previous Grok generation. Coding, agentic software, engineering.",
    recommendedFor: ["alternative", "coding", "agent"],
    domain: "text",
  },
];

// ─── DeepSeek — V4 family ──────────────────────────────────────────
const DEEPSEEK_MODELS: ModelDefinition[] = [
  {
    canonicalId: "deepseek-v4-pro",
    displayName: "DeepSeek V4 Pro",
    provider: "deepseek",
    providerModelId: "deepseek-v4-pro",
    openRouterModelId: "deepseek/deepseek-v4-pro",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 1_048_576,
    pricing: { inputPer1M: 0.435, outputPer1M: 0.87, unit: "per-token" },
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "GA 2026-08-13. Strong agent/tool workflows, native Responses API.",
    recommendedFor: ["agent", "coding", "reasoning", "balanced"],
    littRecommended: true,
    littTier: "agent",
    domain: "text",
    maxOutputTokens: 384_000,
    reasoningEfforts: ["max", "high", "low"],
  },
  {
    canonicalId: "deepseek-v4-flash",
    displayName: "DeepSeek V4 Flash",
    provider: "deepseek",
    providerModelId: "deepseek-v4-flash",
    openRouterModelId: "deepseek/deepseek-v4-flash",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 1_048_576,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Fast, cheap agent model. Native Responses API, configurable thinking.",
    recommendedFor: ["agent", "fast", "cheap"],
    domain: "text",
    reasoningEfforts: ["max", "high", "low"],
  },
];

// ─── Kimi — K3 + K2.7 Code family ──────────────────────────────────
const KIMI_MODELS: ModelDefinition[] = [
  {
    canonicalId: "kimi-k3",
    displayName: "Kimi K3",
    provider: "kimi",
    providerModelId: "kimi-k3",
    openRouterModelId: "moonshotai/kimi-k3",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 1_000_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Kimi flagship. 2.8T params, native vision, 1M context. Long-horizon coding.",
    recommendedFor: ["code-max", "coding", "reasoning", "long-context"],
    littRecommended: true,
    littTier: "code-max",
    domain: "text",
  },
  {
    canonicalId: "kimi-k2.7-code",
    displayName: "Kimi K2.7 Code",
    provider: "kimi",
    providerModelId: "kimi-k2.7-code",
    openRouterModelId: "moonshotai/kimi-k2.7-code",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "normal",
    intelligence: "balanced",
    contextWindow: 256_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Dedicated coding model. Reliable long-context instruction following.",
    recommendedFor: ["coding", "code"],
    domain: "text",
  },
  {
    canonicalId: "kimi-k2.7-code-highspeed",
    displayName: "Kimi K2.7 Code Highspeed",
    provider: "kimi",
    providerModelId: "kimi-k2.7-code-highspeed",
    openRouterModelId: "moonshotai/kimi-k2.7-code-highspeed",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "ultra",
    intelligence: "balanced",
    contextWindow: 256_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "~180 tok/s (up to 260 short-context). Rapid coding loops.",
    recommendedFor: ["code-fast", "coding", "fast"],
    littRecommended: true,
    littTier: "code-fast",
    domain: "text",
  },
  {
    canonicalId: "kimi-k2.6",
    displayName: "Kimi K2.6",
    provider: "kimi",
    providerModelId: "kimi-k2.6",
    openRouterModelId: "moonshotai/kimi-k2.6",
    capabilities: { ...FULL_CHAT, longContext: true },
    speed: "normal",
    intelligence: "balanced",
    contextWindow: 256_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "General model. Vision + text, thinking + non-thinking modes, agent tasks.",
    recommendedFor: ["general", "agent"],
    domain: "text",
  },
];

// ─── Mistral ───────────────────────────────────────────────────────
const MISTRAL_MODELS: ModelDefinition[] = [
  {
    canonicalId: "mistral-medium-3-5",
    displayName: "Mistral Medium 3.5",
    provider: "mistral",
    providerModelId: "mistral-medium-2504",
    openRouterModelId: "mistralai/mistral-medium-3-5",
    capabilities: { ...FULL_CHAT, longContext: false },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 256_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Frontier-class multimodal model for agentic + coding use cases.",
    recommendedFor: ["alternative", "coding", "agent"],
    domain: "text",
  },
  {
    canonicalId: "mistral-small-4",
    displayName: "Mistral Small 4",
    provider: "mistral",
    providerModelId: "mistral-small-2603",
    openRouterModelId: "mistralai/mistral-small-2603",
    capabilities: { ...TEXT_CHAT, longContext: false },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 128_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Efficient hybrid instruct/reasoning/coding model.",
    recommendedFor: ["fast", "balanced", "coding"],
    domain: "text",
  },
];

// ─── Qwen — latest 3.8 (dynamic discovery picks up newer) ──────────
const QWEN_MODELS: ModelDefinition[] = [
  {
    canonicalId: "qwen3.8-max",
    displayName: "Qwen3.8 Max",
    provider: "qwen",
    providerModelId: "qwen3.8-max",
    openRouterModelId: "qwen/qwen3.8-max",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "normal",
    intelligence: "frontier",
    contextWindow: 1_000_000,
    availability: "unverified",
    verified: false,
    verifiedAt: null,
    source: "unverified",
    description: "Qwen flagship. Large MoE, agentic coding + tool use.",
    recommendedFor: ["alternative", "coding", "reasoning", "long-context"],
    domain: "text",
    notes: "Qwen models are discovered dynamically — this entry may be superseded by discovery.",
  },
];

// ─── Free OpenRouter models (zero-cost, rate-limited) ──────────────
// These use OpenRouter's free tier — no credits required on any account.
// Rate-limited but functional for users without funded provider accounts.
const FREE_OPENROUTER_MODELS: ModelDefinition[] = [
  {
    canonicalId: "minimax-m3-free",
    displayName: "MiniMax M3 (Free)",
    provider: "openrouter",
    providerModelId: "minimax/minimax-m3:free",
    openRouterModelId: "minimax/minimax-m3:free",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "normal",
    intelligence: "balanced",
    contextWindow: 1_048_576,
    availability: "online",
    verified: true,
    verifiedAt: "2026-08-27",
    source: "openrouter-catalog",
    description: "Free tier — general purpose, 1M context. Rate-limited.",
    recommendedFor: ["free", "general", "reasoning", "large-context"],
    domain: "text",
    notes: "OpenRouter free model. No credits required. Rate-limited upstream.",
  },
  {
    canonicalId: "glm-5.2-free",
    displayName: "GLM-5.2 (Free)",
    provider: "openrouter",
    providerModelId: "z-ai/glm-5.2:free",
    openRouterModelId: "z-ai/glm-5.2:free",
    capabilities: { ...TEXT_CHAT, longContext: true },
    speed: "fast",
    intelligence: "balanced",
    contextWindow: 262_144,
    availability: "online",
    verified: true,
    verifiedAt: "2026-08-27",
    source: "openrouter-catalog",
    description: "Free tier — coding + reasoning, 256K context. Rate-limited.",
    recommendedFor: ["free", "coding", "reasoning"],
    domain: "text",
    notes: "OpenRouter free model. No credits required. Rate-limited upstream.",
  },
  {
    canonicalId: "gemma-4-31b-free",
    displayName: "Gemma 4 31B (Free)",
    provider: "openrouter",
    providerModelId: "google/gemma-4-31b-it:free",
    openRouterModelId: "google/gemma-4-31b-it:free",
    capabilities: { ...TEXT_CHAT },
    speed: "fast",
    intelligence: "light",
    contextWindow: 262_144,
    availability: "online",
    verified: true,
    verifiedAt: "2026-08-27",
    source: "openrouter-catalog",
    description: "Free tier — Google open model, 262K context. Rate-limited.",
    recommendedFor: ["free", "general", "fast"],
    domain: "text",
    notes: "OpenRouter free model. No credits required. Rate-limited upstream.",
  },
];

// ─── The full V1 catalog ───────────────────────────────────────────
export const MODEL_CATALOG: ModelDefinition[] = [
  ...OPENAI_MODELS,
  ...ANTHROPIC_MODELS,
  ...GOOGLE_MODELS,
  ...XAI_MODELS,
  ...DEEPSEEK_MODELS,
  ...KIMI_MODELS,
  ...MISTRAL_MODELS,
  ...QWEN_MODELS,
  ...FREE_OPENROUTER_MODELS,
];

// ─── LiTT defaults (spec section 24) ───────────────────────────────
export const LITT_DEFAULTS = {
  /** LiTT Default Mode. */
  mode: "auto" as const,
  /** Fast default — default chat, quick tasks, rapid agent loops. */
  fast: "gpt-5.6-luna",
  /** Balanced escalation — everyday coding + stronger reasoning. */
  balanced: "gpt-5.6-terra",
  /** Maximum escalation — hardest coding, planning, reasoning. */
  max: "gpt-5.6-sol",
  /** Fast coding alternative — rapid coding loops. */
  codeFast: "kimi-k2.7-code-highspeed",
  /** Large-repo coding alternative — long-horizon coding. */
  codeMax: "kimi-k3",
} as const;
