/**
 * Browser launcher — opens the system browser to the Clerk OAuth URL.
 *
 * Desktop:
 *   - macOS:   `open <url>`
 *   - Windows: `cmd /c start "" "<url>"` (via exec, not spawn)
 *   - Linux:   `xdg-open <url>`
 *
 * Termux/Android:
 *   - `termux-open-url <url>` (if Termux:API is installed)
 *
 * If opening the browser fails, the URL is printed so the user can
 * tap/copy it manually. The Android browser redirect to 127.0.0.1:{port}
 * returns to the one-shot HTTP listener running inside Termux.
 */

import { spawn, exec, execSync } from "node:child_process";
import { AuthError } from "./types.js";

/** Check if we're running inside Termux on Android. */
export function isTermux(): boolean {
  return !!process.env.TERMUX_VERSION || (process.env.PREFIX?.includes("/com.termux/") ?? false);
}

/** Check if a command exists in PATH (synchronous, best-effort). */
function hasCommand(cmd: string): boolean {
  try {
    execSync(`${cmd} --version`, { stdio: "ignore", timeout: 3000 });
    return true;
  } catch {
    try {
      execSync(`which ${cmd}`, { stdio: "ignore", timeout: 3000 });
      return true;
    } catch {
      return false;
    }
  }
}

/**
 * Build the Windows command string for opening a URL via `start`.
 *
 * `start` is a cmd.exe builtin — it cannot be called via spawn() without
 * going through cmd.exe. Using spawn() with args causes Node.js to apply
 * its own argument escaping, which mangles the literal double-quotes we
 * need around the URL, producing paths like `"https://..."` (with quotes
 * as literal characters) and triggering "Windows cannot find" dialogs.
 *
 * Using exec() passes the command string directly to cmd.exe's parser,
 * so `start "" "https://..."` is interpreted correctly:
 *   - `""` is the window title (start's first quoted arg is the title)
 *   - `"https://..."` is the URL, quoted to protect `&` from cmd.exe's
 *     command separator
 *
 * The URL is generated by our own OAuth code (not user input), but we
 * strip any literal double-quotes as defense in depth.
 */
export function buildWindowsStartCommand(url: string): string {
  const safeUrl = url.replace(/"/g, "");
  return `start "" "${safeUrl}"`;
}

/**
 * Open a URL in the system browser.
 *
 * On failure, prints the URL so the user can open it manually.
 * Never throws — browser-open failure is non-fatal (manual URL fallback).
 */
export async function openBrowser(url: string): Promise<void> {
  const platform = process.platform;

  // ─── Termux/Android ────────────────────────────────────────────
  if (isTermux()) {
    if (hasCommand("termux-open-url")) {
      try {
        const child = spawn("termux-open-url", [url], { detached: true, stdio: "ignore" });
        child.unref();
        return;
      } catch {
        // Fall through to manual URL
      }
    }
    // termux-open-url not available — print URL for manual open
    console.log(`\n  Could not open browser automatically.`);
    console.log(`  Open this URL to sign in:\n  ${url}\n`);
    return;
  }

  // ─── Windows ───────────────────────────────────────────────────
  // `start` is a cmd.exe builtin, so we must go through cmd.exe's command
  // parser. Using spawn() with args causes Node.js to re-escape the literal
  // double-quotes, mangling the URL. exec() passes the string directly to
  // cmd.exe, preserving the correct quoting.
  if (platform === "win32") {
    try {
      await new Promise<void>((resolve, reject) => {
        const child = exec(buildWindowsStartCommand(url), {
          windowsHide: true,
          timeout: 5000,
        }, (err) => {
          if (err) reject(err);
          else resolve();
        });
      });
      return;
    } catch {
      console.log(`\n  Could not open browser automatically.`);
      console.log(`  Open this URL to sign in:\n  ${url}\n`);
      return;
    }
  }

  // ─── macOS / Linux desktop ─────────────────────────────────────
  const command = platform === "darwin" ? "open" : "xdg-open";

  try {
    await new Promise<void>((resolve, reject) => {
      const child = spawn(command, [url], { detached: true, stdio: "ignore" });
      child.once("error", (err) => reject(err));
      child.unref();
      // Give the spawn a moment to succeed, then resolve
      setTimeout(resolve, 500);
    });
  } catch {
    // Browser open failed — print URL for manual open
    console.log(`\n  Could not open browser automatically.`);
    console.log(`  Open this URL to sign in:\n  ${url}\n`);
  }
}
